### ISSUE TITLE
Settings / Configuration Module

### ISSUE THREAD

**Issue by scottcrespo** [picardrulez/eps-conduit#5]
Currently there are a number command-line flags to run Conduit. I would like to see some of these flags offloaded to a settings/configuration file that is written in plain text or json that's easy to manage. To run Conduit, the user would pass in the configuration file name as the only required flag. 

I think this approach will make the system more user-friendly, and allow us to add new, configurable features without complicating the command line interface.

Does this seem like a viable feature to develop?

**Comment by picardrulez** [comment]
adding this comment to issue#2
